package com.model;

/**
 * Represents the different credentials a user can have.
 * @author Olivia Casper
 */
public enum Credential {
    PHYSICIAN,
    CERTIFIED_REGISTERED_NURSE_ANESTHETIST,
    REGISTERED_NURSE,
    CERTIFIED_EMERGENCY_NURSE,
    PHYSICIAN_ASSISTANT,
    NURSE_PRACTITIONER,
    PARAMEDIC,
    EMERGENCY_MEDICAL_TECHNICIAN_BASIC,
    BASIC_LIFE_SUPPORT,
    ADVANCED_CARDIAC_LIFE_SUPPORT,
    PEDIATRIC_ADVANCED_LIFE_SUPPORT,
    FEDERAL_EMERGENCY_MANAGEMENT_AGENCY,
    DISASTER_MEDICAL_ASSISTANCE_TEAM,
    URBAN_SEARCH_AND_RESCUE
}
